### ISSUE TITLE
Conduct user interviews and come up with a Persona

### ISSUE THREAD

**Issue by jisie** [nss-day-cohort-24/theme-park-slippery-lightyears#12]
Interview at least three parents who have children to understand what kind of experience they would like when they visit a theme park and come up with a persona.

**Comment by BlueprintMage** [comment]
This has been accomplished. We developed two different personas:

1. "G.G Force" 

2. "Chase Lounger"


We also conducted User Interviews with both clients and potential theme park attendees.

**Comment by PhonethipLiu** [comment]
Revisiting interviewing process to fit requirements.

**Comment by PhonethipLiu** [comment]
Resubmitted a revised persona. Has Peter Griffin as the primary persona now.
